### ISSUE TITLE
Closes

### ISSUE THREAD

**Issue by ghost** [Hephyrius/Binance-Triangular-Arbitrage-Bot#4]
Hello, the programme automatically closes after some time. How to let it run, for example a few hours without a break?

**Comment by Hephyrius** [comment]
I will look into this. If i remember correctly this is related to decimal places. binance uses a weird range thats market specific. it ranges 1-5 dp's

**Comment by Hephyrius** [comment]
I will commit my fix once I've tested it

**Comment by ghost** [comment]
Thanks.
